baseURL = 'https://nabla-memo.vercel.app/'
languageCode = 'en-us'
title = 'Nabla Memo'
theme = 'ananke'

[params]
  description = 'Sample Hugo site deployable with Vercel'
  author = 'Nabla Team'

[params.homeInfoParams]
  Title = 'Welcome to Nabla Memo'
  Content = 'A Hugo site deployed with Vercel'

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 2

# [module]
# [[module.imports]]
# disable = false
# ignoreConfig = false
# ignoreImports = false
# path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
